service: appointment-service
provider:
  name: aws
  runtime: nodejs22.x

functions:
  createAppointmentMedical:
    handler: src/infrastructure/adapters/lambdas/createAppointment.ts
    events:
      - http:
          path: appointments
          method: post

  listAppointmentsMedical:
    handler: src/infrastructure/adapters/lambdas/listAppointments.handler
    events:
      - http:
          path: appointments/{insuredId}
          method: get

  appointmentMedicalPe:
    handler: src/infrastructure/adapters/lambdas/appointmentCL-PE.handler
    events:
      - sqs:
          arn: !GetAtt AppointmentSQSPEQueue.Arn

  appointmentMedicalCl:
    handler: src/infrastructure/adapters/lambdas/appointmentCL-PE.handler
    events:
      - sqs:
          arn: !GetAtt AppointmentSQSCLQueue.Arn

  completeAppointmentMedical:
    handler: src/infrastructure/handlers/finalAppointment.handler
    events:
      - sqs:
          arn: !GetAtt SQSConfirmation.Arn

resources:
  Resources:
    # Tabla DynamoDB
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Appointments
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
          - AttributeName: appointmentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # SNS Topic
    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: medical-appointment-topic

    # SQS PE
    AppointmentSQSPEQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-medical-appointment_pe
    # SQS CL
    AppointmentSQSCLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-medical-appointment_cl

    # Suscripciones SNS a SQS con Filtro por País (Paso 3)
    SNSToSQSPESubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Endpoint: !GetAtt AppointmentSQSPEQueue.Arn
        Protocol: sqs
        FilterPolicy:
          countryISO:
            - PE

    SNSToSQSCLSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Endpoint: !GetAtt AppointmentSQSCLQueue.Arn
        Protocol: sqs
        FilterPolicy:
          countryISO:
            - CL

    # SQS para recibir la conformidad final (Paso 5)
    SQSConfirmation:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_Confirmation

    # Regla de EventBridge (Paso 5)
    EventBridgeToSQSRule:
      Type: AWS::Events::Rule
      Properties:
        Description: "Captura confirmaciones regionales y las manda a SQS"
        EventPattern:
          source:
            - "custom.appointments"
          detail-type:
            - "AppointmentConfirmed"
        Targets:
          - Arn: !GetAtt SQSConfirmation.Arn
            Id: "SQSConfirmationTarget"