service: appointment-medical

custom:
  tableName: Appointments
  topicName: medical-appointment-topic
  eventBusName: custom-appointments
  peQueueName: sqs-medical-appointment-pe
  clQueueName: sqs-medical-appointment-cl
  confirmationQueueName: sqs-confirmation

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  apiGateway:
    apiKeys:
      - name: medical-appointment-key-${self:provider.stage}

  environment:
    TABLE_NAME: ${self:custom.tableName}
    TOPIC_ARN: !Ref AppointmentTopic
    EVENT_BUS_NAME: ${self:custom.eventBusName}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - !GetAtt AppointmentsTable.Arn
        #Permisos para publicar en SNS
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref AppointmentTopic
        #Permisos para enviar messages en SQS
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt AppointmentSQSPEQueue.Arn
            - !GetAtt AppointmentSQSCLQueue.Arn
            - !GetAtt SQSConfirmation.Arn
        # Permisos para EventBridge
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: '*'

plugins:
  - serverless-offline
  - serverless-jetpack

functions:
  createAppointment:
    handler: dist/infrastructure/adapters/lambdas/createAppointment.handler
    events:
      - http:
          path: appointments
          method: post
          cors: true
          private: true

  listAppointments:
    handler: dist/infrastructure/adapters/lambdas/listAppointment.handler
    events:
      - http:
          path: appointments/{insuredId}
          method: get
          cors: true
          private: true

  processAppointmentPE:
    handler: dist/infrastructure/adapters/lambdas/appointmentCL-PE.handler
    events:
      - sqs:
          arn: !GetAtt AppointmentSQSPEQueue.Arn

  processAppointmentCL:
    handler: dist/infrastructure/adapters/lambdas/appointmentCL-PE.handler
    events:
      - sqs:
          arn: !GetAtt AppointmentSQSCLQueue.Arn

  processAppointmentFinal:
    handler: dist/infrastructure/adapters/lambdas/finalAppointment.handler
    events:
      - sqs:
          arn: !GetAtt SQSConfirmation.Arn

resources:
  Resources:
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
          - AttributeName: appointmentId
            KeyType: RANGE

    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}

    AppointmentSQSPEQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.peQueueName}

    AppointmentSQSCLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.clQueueName}

    SQSConfirmation:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.confirmationQueueName}

    AppointmentSQSPEQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref AppointmentSQSPEQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: 'sns.amazonaws.com'
              Action: 'sqs:SendMessage'
              Resource: !GetAtt AppointmentSQSPEQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentTopic

    AppointmentSQSCLQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref AppointmentSQSCLQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: 'sns.amazonaws.com'
              Action: 'sqs:SendMessage'
              Resource: !GetAtt AppointmentSQSCLQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentTopic

    AppointmentSQSConfirmartionQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SQSConfirmation
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: 'sns.amazonaws.com'
              Action: 'sqs:SendMessage'
              Resource: !GetAtt SQSConfirmation.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentTopic

    SNSToSQSPESubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Endpoint: !GetAtt AppointmentSQSPEQueue.Arn
        Protocol: sqs
        FilterPolicy:
          countryISO:
            - PE

    SNSToSQSCLSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref AppointmentTopic
        Endpoint: !GetAtt AppointmentSQSCLQueue.Arn
        Protocol: sqs
        FilterPolicy:
          countryISO:
            - CL

    SNSToSQSConfirmationSubscription:
          Type: AWS::SNS::Subscription
          Properties:
            TopicArn: !Ref AppointmentTopic
            Endpoint: !GetAtt SQSConfirmation.Arn
            Protocol: sqs

    EventBridgeToSQSRule:
      Type: AWS::Events::Rule
      Properties:
        State: ENABLED
        Description: 'Captura confirmaciones y envía a SQS'
        EventPattern:
          source:
            - custom.appointments
          detail-type:
            - AppointmentConfirmed
        Targets:
          - Arn: !GetAtt SQSConfirmation.Arn
            Id: SQSConfirmationTarget
